-- ChargeGrid: schema inicial (Etapa 1 da proposta: "PostgreSQL registra usuarios,
-- estacoes, carregadores, sessoes, pagamentos e eventos").
--
-- Espelha backend/app/models.py. Se alterar um modelo, altere aqui e crie uma NOVA
-- migration (nao edite esta depois de aplicada).
--
-- SEGURANCA: o Supabase expoe as tabelas do schema public via API REST (PostgREST) usando
-- a chave "anon"/"publishable". Este projeto NAO usa essa API -- so o backend FastAPI
-- fala com o banco (com o usuario postgres, que ignora RLS). Por isso ligamos RLS em
-- todas as tabelas SEM nenhuma policy: com isso a chave publica nao enxerga nada.
-- Horarios: todas as colunas de data/hora estao em UTC ("timestamp" sem fuso).

create table public.users (
    id            integer generated by default as identity primary key,
    name          varchar(120) not null,
    email         varchar(180) not null unique,
    password_hash varchar(255) not null,
    role          varchar(20)  not null default 'driver' check (role in ('driver', 'operator')),
    created_at    timestamp    not null default (now() at time zone 'utc')
);

create table public.vehicles (
    id      integer generated by default as identity primary key,
    user_id integer      not null references public.users (id),
    plate   varchar(20)  not null,
    model   varchar(80)  not null
);
create index vehicles_user_id_idx on public.vehicles (user_id);

create table public.stations (
    id             integer generated by default as identity primary key,
    name           varchar(120)     not null,
    type           varchar(20)      not null check (type in ('comercial', 'residencial')),
    address        varchar(200)     not null default '',
    power_limit_kw double precision not null default 35,
    profile_key    varchar(40)      not null default 'chargegrid_intelligence'
);

create table public.chargers (
    id             integer generated by default as identity primary key,
    station_id     integer          not null references public.stations (id),
    code           varchar(20)      not null unique,
    name           varchar(80)      not null default '',
    connector_type varchar(20)      not null default 'Type 2 AC',
    status         varchar(20)      not null default 'livre' check (status in ('livre', 'ocupado', 'manutencao')),
    max_power_kw   double precision not null default 22
);
create index chargers_station_id_idx on public.chargers (station_id);

create table public.charging_sessions (
    id                     integer generated by default as identity primary key,
    user_id                integer          not null references public.users (id),
    vehicle_id             integer          references public.vehicles (id),
    charger_id             integer          not null references public.chargers (id),
    mode                   varchar(20)      not null default 'rapido'
                           check (mode in ('rapido', 'economico', 'sustentavel', 'garantido')),

    vehicle_label          varchar(80),
    target_pct             integer          check (target_pct between 1 and 100),
    departure_time         varchar(5),

    -- variaveis da maquina de estados (Sprint 3 - logica booleana do ESP32)
    payment_confirmed      boolean          not null default false, -- A
    rfid_ok                boolean          not null default false, -- B
    cable_connected        boolean          not null default false, -- C
    maintenance_bypass     boolean          not null default false, -- M
    payment_finalized      boolean          not null default false, -- D

    started_at             timestamp        not null default (now() at time zone 'utc'),
    charging_started_at    timestamp,
    ended_at               timestamp,

    energy_kwh             double precision not null default 0,
    current_power_kw       double precision not null default 0,
    current_pct            double precision not null default 0,
    last_meter_at          timestamp,

    price_per_kwh_snapshot double precision not null default 0,
    amount_due             double precision not null default 0
);
create index charging_sessions_user_id_idx    on public.charging_sessions (user_id);
create index charging_sessions_charger_id_idx on public.charging_sessions (charger_id);
create index charging_sessions_open_idx       on public.charging_sessions (charger_id) where ended_at is null;

create table public.session_events (
    id           integer generated by default as identity primary key,
    session_id   integer     not null references public.charging_sessions (id),
    type         varchar(60) not null,
    payload_json jsonb       not null default '{}'::jsonb,
    created_at   timestamp   not null default (now() at time zone 'utc')
);
create index session_events_session_id_idx on public.session_events (session_id);

create table public.payments (
    id           integer generated by default as identity primary key,
    session_id   integer          not null references public.charging_sessions (id),
    method       varchar(20)      not null check (method in ('pix', 'cartao')),
    status       varchar(20)      not null default 'pendente' check (status in ('pendente', 'aprovado', 'recusado')),
    amount       double precision not null,
    provider_ref varchar(60)      not null default '',
    created_at   timestamp        not null default (now() at time zone 'utc')
);
create index payments_session_id_idx on public.payments (session_id);

create table public.goodwe_readings (
    id          integer generated by default as identity primary key,
    station_id  integer          not null references public.stations (id),
    origem      varchar(20)      not null default 'simulado' check (origem in ('simulado', 'real')),
    timestamp   timestamp        not null default (now() at time zone 'utc'),
    power_kw    double precision not null,
    soc_percent double precision,
    raw_json    jsonb            not null default '{}'::jsonb
);
create index goodwe_readings_station_id_idx on public.goodwe_readings (station_id, id desc);

create table public.integration_logs (
    id           integer generated by default as identity primary key,
    source       varchar(40) not null,
    level        varchar(10) not null,
    message      text        not null,
    payload_json jsonb       not null default '{}'::jsonb,
    created_at   timestamp   not null default (now() at time zone 'utc')
);

-- ---------------------------------------------------------------------------
-- RLS ligado em tudo, sem policies => chaves anon/publishable nao leem nem escrevem.
-- ---------------------------------------------------------------------------
alter table public.users             enable row level security;
alter table public.vehicles          enable row level security;
alter table public.stations          enable row level security;
alter table public.chargers          enable row level security;
alter table public.charging_sessions enable row level security;
alter table public.session_events    enable row level security;
alter table public.payments          enable row level security;
alter table public.goodwe_readings   enable row level security;
alter table public.integration_logs  enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
