-- ChargeGrid: IA no preco e na previsao de demanda (playbook GoodWe: "IA aplicada").
--
-- 1) A sessao guarda DE ONDE veio o preco travado e a ocupacao usada (aparece no comprovante).
--    Sessoes antigas ficam como 'curva' (preco pela curva horaria da versao anterior).
-- 2) forecast_models: uma linha por versao do modelo de previsao (parametros + metricas do treino).
--
-- Idempotente. RLS ligado sem policies (so o backend acessa, como nas demais tabelas).

alter table public.charging_sessions
    add column if not exists price_source    varchar(24) not null default 'curva',
    add column if not exists price_occupancy double precision;

create table if not exists public.forecast_models (
    id           integer generated by default as identity primary key,
    version      integer     not null,
    source       varchar(20) not null check (source in ('csv', 'padrao')),
    trained_at   timestamp   not null default (now() at time zone 'utc'),
    rows         integer     not null default 0,
    params_json  jsonb       not null default '{}'::jsonb,
    metrics_json jsonb       not null default '{}'::jsonb
);
create unique index if not exists forecast_models_version_idx on public.forecast_models (version);

alter table public.forecast_models enable row level security;
