-- ChargeGrid: mensagens OCPP 1.6J trocadas com os carregadores (pilar "Protocolos abertos" do playbook GoodWe).
--
-- Uma linha por quadro OCPP, entrada ou saida. Alimenta a tela "Logs OCPP" com mensagens reais.
-- O backend apaga as mais antigas que OCPP_MESSAGE_RETENTION_DAYS ao subir.
--
-- Idempotente. RLS ligado sem policies (so o backend acessa, como nas demais tabelas).

create table if not exists public.ocpp_messages (
    id              integer generated by default as identity primary key,
    charge_point_id varchar(20) not null,
    direction       varchar(3)  not null check (direction in ('in', 'out')),
    message_type    integer     not null,
    action          varchar(40) not null default '',
    unique_id       varchar(40) not null default '',
    payload_json    jsonb       not null default '{}'::jsonb,
    created_at      timestamp   not null default (now() at time zone 'utc')
);
create index if not exists ocpp_messages_charge_point_id_idx on public.ocpp_messages (charge_point_id);
create index if not exists ocpp_messages_created_at_idx on public.ocpp_messages (created_at);

alter table public.ocpp_messages enable row level security;
